### ISSUE TITLE
add option to add custom character

### ISSUE THREAD

**Issue by jsena1** [jsena1/groupproject-code-monkeys#3]
Improved character select options:
add more character options and improve the character select screen by changing the function into a text file and displaying each avaiable character as a line of text. a preview of the character is displayed below through a function that listens for clicking on an element and displays the character beneath by retrieving the image file name associated with the text that was clicked

**Comment by onzfonz** [comment]
This needs more detail in general with regards to the assignment (ended up asking for more here), but I'm going to have you do this one.

For the image file what I would rather you do is to have a text file that has the image files for the characters as options, and then they could click on the one that they like
Or you could have all of the images in a directory initially and they would be displayed, and then they can click on one for it to be shown.

**Comment by jsena1** [comment]
oh ok so like this?
Improved character select options:
add more character options and improve the character select screen by changing the function into a text file and displaying each avaiable character as a line of text. a preview of the character is displayed below through a function that listens for clicking on an element and displays the character beneath by retrieving the image file name associated with the text that was clicked
